// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvsphknghblwxbeysazy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2c3Boa25naGJsd3hiZXlzYXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTY0NDQsImV4cCI6MjA2NjA3MjQ0NH0._Mb64gaOqiVA0r4A6kT-rh-q1n9EeTQI2L0Eyj_1n4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);